# only add install rules if the target is built
IF(${BUILD_${target}})
    FILE(RELATIVE_PATH dest_dir ${CMAKE_SOURCE_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
    SET(OUT_DIR "${SNAP_INSTALL_PREFIX}/${dest_dir}")
    INSTALL(TARGETS ${target} 
            DESTINATION ${OUT_DIR}            
            PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    INSTALL(FILES ${_DATA} DESTINATION "${OUT_DIR}/data" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)      
ENDIF()

  
 